### ISSUE TITLE
hard return after pipe

### ISSUE THREAD

**Issue by ben-williams** [commfish/coho_known_age_study#3]
https://github.com/commfish/coho_known_age_study/blob/4ae222e587e147f41ff6c8a15f6ae776d289006e/code/LDA_JTP_DataImport.R#L29

For clarity and to follow along with our conventions could you please place a hard return after a pipe (similarly, a hard return after a + in ggplot) 

Here is an example https://github.com/commfish/weiRends/blob/master/code/functions.r

Thanks!

**Comment by justinpriest** [comment]
If I'm understanding this correctly, you're asking to have no comments after a pipe, correct? 
Move comments to their own line after each code line?

**Comment by justinpriest** [comment]
@ben-williams Nevermind, I understand it now. Apparently my brain was fried at 5 PM on Friday.
