### ISSUE TITLE
reshape2 package is not maintained

### ISSUE THREAD

**Issue by fssem1** [commfish/coho_known_age_study#4]
Might be better to move to gather and spread in tidyverse.

https://github.com/commfish/coho_known_age_study/blob/da03a47cbb4118d0c855c965eae07e01df123e86/code/LDA_JTP_DataImport.R#L50

**Comment by justinpriest** [comment]
It is. I couldn't find a simple way to use tidyr to sum while using spread. If that's worth spending the extra time, I can do that.

**Comment by justinpriest** [comment]
OK I found a workaround. Much simpler than I anticipated. Closing issue now.
